//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigStartAs.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigStartAs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hidden.
        /// </summary>
        public static string cbWsHidden {
            get {
                return ResourceManager.GetString("cbWsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximized.
        /// </summary>
        public static string cbWsMaximized {
            get {
                return ResourceManager.GetString("cbWsMaximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal window.
        /// </summary>
        public static string cbWsNormal {
            get {
                return ResourceManager.GetString("cbWsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduced.
        /// </summary>
        public static string cbWsReduced {
            get {
                return ResourceManager.GetString("cbWsReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arguments:.
        /// </summary>
        public static string lblArgs {
            get {
                return ResourceManager.GetString("lblArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string lblBtnBrowse {
            get {
                return ResourceManager.GetString("lblBtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        public static string lblBtnNew {
            get {
                return ResourceManager.GetString("lblBtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open….
        /// </summary>
        public static string lblBtnOpenDotted {
            get {
                return ResourceManager.GetString("lblBtnOpenDotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string lblBtnSave {
            get {
                return ResourceManager.GetString("lblBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify.
        /// </summary>
        public static string lblBtnVerify {
            get {
                return ResourceManager.GetString("lblBtnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set an expiration date for the authentication file.
        /// </summary>
        public static string lblCbSetExpirationDate {
            get {
                return ResourceManager.GetString("lblCbSetExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perform an integrity check on the executable at launch (may slow down the startup).
        /// </summary>
        public static string lblCbSetVerifAtStart {
            get {
                return ResourceManager.GetString("lblCbSetVerifAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ask for a PIN code when starting the application.
        /// </summary>
        public static string lblCvSetPin {
            get {
                return ResourceManager.GetString("lblCvSetPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target:.
        /// </summary>
        public static string lblExecFilePath {
            get {
                return ResourceManager.GetString("lblExecFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication file.
        /// </summary>
        public static string lblFileAuthent {
            get {
                return ResourceManager.GetString("lblFileAuthent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security.
        /// </summary>
        public static string lblGpSecurity {
            get {
                return ResourceManager.GetString("lblGpSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start as.
        /// </summary>
        public static string lblGpStartAs {
            get {
                return ResourceManager.GetString("lblGpStartAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password:.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username:.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start in:.
        /// </summary>
        public static string lblWdDir {
            get {
                return ResourceManager.GetString("lblWdDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the password.
        /// </summary>
        public static string lblWinPwdPrompt {
            get {
                return ResourceManager.GetString("lblWinPwdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password required to open authentification file.
        /// </summary>
        public static string lblWinPwdPromptTitle {
            get {
                return ResourceManager.GetString("lblWinPwdPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string lblWs {
            get {
                return ResourceManager.GetString("lblWs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Powershell has been selected. Do you want to choose to run a *.ps1 script (must be accessible by the target user)?.
        /// </summary>
        public static string msgAskForPs1 {
            get {
                return ResourceManager.GetString("msgAskForPs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication file saved.
        /// </summary>
        public static string msgAuthentFileSaved {
            get {
                return ResourceManager.GetString("msgAuthentFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This authentication file is temporary; it cannot be edited..
        /// </summary>
        public static string msgTxtCantEditTempAuthFile {
            get {
                return ResourceManager.GetString("msgTxtCantEditTempAuthFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changes may have been made to file &apos;{0}&apos;. If you open another file, you may lose these changes. Do you want to continue?.
        /// </summary>
        public static string msgTxtChangesPending {
            get {
                return ResourceManager.GetString("msgTxtChangesPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The directory &apos;{0}&apos; does not exist or is not accessible..
        /// </summary>
        public static string msgTxtDirNotExist {
            get {
                return ResourceManager.GetString("msgTxtDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string msgTxtError {
            get {
                return ResourceManager.GetString("msgTxtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error when creating the authentication file..
        /// </summary>
        public static string msgTxtErrorCreateAuthentFile {
            get {
                return ResourceManager.GetString("msgTxtErrorCreateAuthentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For security reasons, the CRT file will not be opened..
        /// </summary>
        public static string msgTxtErrorOpenAuthFileGen {
            get {
                return ResourceManager.GetString("msgTxtErrorOpenAuthFileGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect password. For security reasons, the CRT file will not be opened..
        /// </summary>
        public static string msgTxtErrorOpenAuthFilePwd {
            get {
                return ResourceManager.GetString("msgTxtErrorOpenAuthFilePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error reading authentication file.
        /// </summary>
        public static string msgTxtErrorReadingAuthFile {
            get {
                return ResourceManager.GetString("msgTxtErrorReadingAuthFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file &apos;{0}&apos; does not exist or is not accessible..
        /// </summary>
        public static string msgTxtFileNotExist {
            get {
                return ResourceManager.GetString("msgTxtFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string msgTxtInfo {
            get {
                return ResourceManager.GetString("msgTxtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The authentication file &apos;{0}&apos; has been created. You can open the folder containing it or create a shortcut on the desktop..
        /// </summary>
        public static string msgTxtOkSavedNew {
            get {
                return ResourceManager.GetString("msgTxtOkSavedNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The authentication file &apos;{0}&apos; has been saved. You can open the folder containing it or create a shortcut on the desktop..
        /// </summary>
        public static string msgTxtOkSavedNotNew {
            get {
                return ResourceManager.GetString("msgTxtOkSavedNotNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        public static string msgTxtQuestion {
            get {
                return ResourceManager.GetString("msgTxtQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User exists on this computer.
        /// </summary>
        public static string msgTxtUserExists {
            get {
                return ResourceManager.GetString("msgTxtUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User does not exist on this computer.
        /// </summary>
        public static string msgTxtUserNotExists {
            get {
                return ResourceManager.GetString("msgTxtUserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It is mandatory to enter a password in order to read the CRT file..
        /// </summary>
        public static string msgTxtWarnNoPwd {
            get {
                return ResourceManager.GetString("msgTxtWarnNoPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication files|*.crt|All files|*.*.
        /// </summary>
        public static string openForAuthFileFilter {
            get {
                return ResourceManager.GetString("openForAuthFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executables|*.exe|All files|*.*.
        /// </summary>
        public static string openForFilePathFilenameFilter {
            get {
                return ResourceManager.GetString("openForFilePathFilenameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PowerShell Script|*.ps1|All files|*.*.
        /// </summary>
        public static string openForFilePs1FilenameFilter {
            get {
                return ResourceManager.GetString("openForFilePs1FilenameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No executable file has been specified..
        /// </summary>
        public static string strNoFileExec {
            get {
                return ResourceManager.GetString("strNoFileExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a shortcut on the desktop.
        /// </summary>
        public static string txtHlinkCreateShortcut {
            get {
                return ResourceManager.GetString("txtHlinkCreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show the authentication file in the explorer.
        /// </summary>
        public static string txtHlinkShowFolderAuthentFileExplorer {
            get {
                return ResourceManager.GetString("txtHlinkShowFolderAuthentFileExplorer", resourceCulture);
            }
        }
    }
}
